### ISSUE TITLE
Добавить фильтрацию на страницу с задачами

### ISSUE THREAD

**Issue by foofaev** [alex-popov-tech/backend-project-lvl4#11]
На странице с задачами не хватает фильтрации.
Нужны фильтры по статусу, исполнителю, наличию метки
Нужна галочка "задачи назначенные на меня", который показывает назначенные на залогиненного пользователя задачи

**Comment by alex-popov-tech** [comment]
working here https://github.com/alex-popov-tech/backend-project-lvl4/pull/25

**Comment by alex-popov-tech** [comment]
and here then #37
