### ISSUE TITLE
feat: factories implementation

### ISSUE THREAD

**Issue by foofaev** [alex-popov-tech/backend-project-lvl4#13]
Examples:
- https://github.com/thoughtbot/fishery
Reason:
 - Tests know all about database tables structure at the moment. And in case of db migration we would to need to change a lot of tests. Treat your tests more like you treat your code - use abstractions.
 - Also there will be less code in your tests

**Comment by alex-popov-tech** [comment]
`Tests know all about database tables structure at the moment ` - there still be models code, since we are using them for assertions

**Comment by alex-popov-tech** [comment]
add client & factories
