### ISSUE TITLE
feat: introduce idempotency to the tests

### ISSUE THREAD

**Issue by foofaev** [alex-popov-tech/backend-project-lvl4#14]
At the moment there is a cleanup only at the end of the describe module - https://github.com/alex-popov-tech/backend-project-lvl4/blob/64eeb9bcd64db51590d78e9412d9769df6ba2ac2/__tests__/task.test.js#L40

Reason:
 - Simple tests, like CRUD tests, should be separated from each other . Any data left from previous tests could lead to unexpected behaviour  in the current one.

Theory:
- https://www.youtube.com/watch?v=lBv_kF4PnEs&t=4s

Example:
- https://github.com/hexlet-boilerplates/fastify-nodejs-application/blob/23bd75dc2fd89a904e01c779a53867c1cb7385a9/__tests__/users.test.js#L65

**Comment by alex-popov-tech** [comment]
its seems to be done in master, right?

**Comment by foofaev** [comment]
https://github.com/alex-popov-tech/backend-project-lvl4/blob/71e3aa30dd276d865862d838cf56435c7929bc8c/__tests__/task.test.js#L18
