### ISSUE TITLE
refactoring: tests setup and teardown

### ISSUE THREAD

**Issue by foofaev** [alex-popov-tech/backend-project-lvl4#22]
names are for readability, if you have to look at the function defintion to undertstand what it does - it's bad naming

_Originally posted by @foofaev in https://github.com/alex-popov-tech/backend-project-lvl4/pull/16#discussion_r586224971_

Please, consider using migrate + rollback instead of trancating every table
Example - https://github.com/hexlet-boilerplates/fastify-nodejs-application/blob/fc27da44dc881721c84365cb55d4cc3e40e8ea30/__tests__/users.test.js#L20-L26

**Comment by alex-popov-tech** [comment]
https://github.com/alex-popov-tech/backend-project-lvl4/pull/23
