### ISSUE TITLE
Добавить пользователей, регистрацию и авторизацию

### ISSUE THREAD

**Issue by foofaev** [alex-popov-tech/backend-project-lvl4#5]
Пользователь должен иметь возможность заходить на сайт с помощью логина и пароля
При регистрации задаются мейл, пароль, имя и фамилия

**Comment by alex-popov-tech** [comment]
users login - https://github.com/alex-popov-tech/backend-project-lvl4/blob/master/server/routes/session.js
users signup - https://github.com/alex-popov-tech/backend-project-lvl4/blob/master/server/routes/users.js
