### ISSUE TITLE
Добавить страницу со списком пользователей

### ISSUE THREAD

**Issue by foofaev** [alex-popov-tech/backend-project-lvl4#8]
Нужна ссылка на главной странице, при нажатии на которую открывается страница со списком пользователей
Точно нужно, чтобы на странице были мейл и имя пользователей, остальное на свое усмотрение

**Comment by alex-popov-tech** [comment]
users list - https://github.com/alex-popov-tech/backend-project-lvl4/blob/master/server/routes/users.js#L3-L6
